# Generated by Django 5.2.7 on 2026-02-04 08:17

import django.db.models.deletion
import django_ulid.models

from django.db import migrations, models
from core.utils import generate_ulid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='purchase_order_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('SHIPPED', 'In Transit'), ('DELIVERED', 'Delivered at Warehouse'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('delivery_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_services', models.CharField(blank=True, max_length=255, null=True)),
                ('comission_fee_pct', models.IntegerField(blank=True, default=0, null=True)),
                ('comission_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('purchase_order_invoice_file', models.FileField(blank=True, null=True, upload_to='po/invoices/')),
                ('delivery_order_file', models.FileField(blank=True, null=True, upload_to='po/delivery_orders/')),
                ('delivery_order_invoice_file', models.FileField(blank=True, null=True, upload_to='po/delivery_invoices/')),
                ('packing_list_file', models.FileField(blank=True, null=True, upload_to='po/packing_lists/')),
                ('total_qty', models.IntegerField(default=0)),
                ('cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shipping_fee_per_cbm', models.BigIntegerField(blank=True, default=0, null=True)),
                ('shipping_fee', models.BigIntegerField(blank=True, default=0, null=True)),
                ('procure_amount', models.BigIntegerField(blank=True, null=True)),
                ('refund_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_item_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_order_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='purchase_order_detail_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('unit_price_foreign', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unit_price_base', models.BigIntegerField(blank=True, null=True)),
                ('total_price_foreign', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('total_price_base', models.BigIntegerField(blank=True, null=True)),
                ('discounted_unit_price_foreign', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('discounted_unit_price_base', models.BigIntegerField(blank=True, null=True)),
                ('discounted_total_price_foreign', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('discounted_total_price_base', models.BigIntegerField(blank=True, null=True)),
                ('incoming_qty', models.IntegerField(default=0)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('avg_sales', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('supplier_link', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='purchasing.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
