# Generated by Django 5.2.7 on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        # 1. Create sequence for PO number generation (per year)
        migrations.RunSQL(
            sql="CREATE SEQUENCE po_number_seq START WITH 1;",
            reverse_sql="DROP SEQUENCE po_number_seq;"
        ),

        # 2. Trigger for PurchaseOrder (PO Number)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_po_number()
            RETURNS TRIGGER AS $$
            DECLARE
                current_year TEXT;
                seq_val INT;
                po_number TEXT;
            BEGIN
                current_year := TO_CHAR(NOW(), 'YYYY');
                seq_val := nextval('po_number_seq');
                
                -- Build PO Number: PO-YYYY-SEQUENCE (padded to 3 digits)
                po_number := 'PO-' || current_year || '-' || LPAD(seq_val::text, 3, '0');
                
                NEW.purchase_order_number := po_number;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_generate_po_number
            BEFORE INSERT ON purchasing_purchaseorder
            FOR EACH ROW
            EXECUTE FUNCTION generate_po_number();
            """,
            reverse_sql="""
            DROP TRIGGER trg_generate_po_number ON purchasing_purchaseorder;
            DROP FUNCTION generate_po_number();
            """
        )
    ]
