# Generated by Django 5.2.7 on 2026-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='updated_qty',
            field=models.IntegerField(default=0),
        ),
    ]
