# Generated by Django 5.2.7 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_delete_invoice_purchaseorderdetail_updated_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='comission_fee_pct',
            new_name='commission_fee_pct',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='comission_fee',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='commission_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_received_qty',
            field=models.IntegerField(default=0),
        ),
    ]
