# Generated by Django 5.2.7 on 2026-03-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_rename_comission_fee_pct_purchaseorder_commission_fee_pct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_qty',
            new_name='total_ordered_qty',
        ),
    ]
