# Generated by Django 5.2.7 on 2026-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_rename_total_qty_to_total_ordered_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('SHIPPED', 'In Transit'), ('DELIVERED', 'Delivered at Warehouse'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
    ]
