# Generated by Django 5.2.7 on 2026-04-26 05:33

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_add_allocated_fees_to_product_cogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sales_order_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('marketplace_order_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('marketplace_order_number', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('shipping_province', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100)),
                ('order_date', models.DateTimeField()),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, default='', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_fee', models.BigIntegerField(default=0)),
                ('shipping_fee_seller', models.BigIntegerField(default=0)),
                ('subtotal', models.BigIntegerField(default=0)),
                ('total_discount', models.BigIntegerField(default=0)),
                ('total_marketplace_fee', models.BigIntegerField(default=0)),
                ('total_cogs', models.BigIntegerField(default=0)),
                ('net_revenue', models.BigIntegerField(default=0)),
                ('gross_profit', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketplace')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sales_order_item_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.BigIntegerField()),
                ('discount_amount', models.BigIntegerField(default=0)),
                ('commission_fee', models.BigIntegerField(default=0)),
                ('service_fee', models.BigIntegerField(default=0)),
                ('total_marketplace_fee', models.BigIntegerField(default=0)),
                ('actual_cogs_per_unit', models.BigIntegerField(default=0)),
                ('actual_cogs_total', models.BigIntegerField(default=0)),
                ('line_total', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderCogsDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sales_order_cogs_detail_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('quantity_consumed', models.IntegerField()),
                ('cogs_per_unit', models.BigIntegerField()),
                ('total_cogs', models.BigIntegerField()),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_cogs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productcogs')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_details', to='sales.salesorderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sales_return_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(default='', editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('RECEIVED', 'Stock Returned'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='sales_return_item_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('reversed_cogs_total', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
