# Generated by Django 5.2.7 on 2026-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_so_return_number_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source_platform',
            field=models.CharField(choices=[('SHOPEE', 'Shopee'), ('TIKTOK', 'TikTok'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10),
        ),
    ]
