# Generated by Django 5.2.7 on 2026-04-27 11:54

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shopee', '0001_initial'),
        ('tiktok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('cs', 'Customer Service'), ('warehouse', 'Warehouse'), ('finance', 'Finance'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceConnection',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='connection_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('SHOPEE', 'Shopee'), ('TIKTOK', 'TikTok Shop')], max_length=32)),
                ('display_name', models.CharField(blank=True, help_text="e.g. 'Brand A Shopee Official'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_connections', to='core.company')),
                ('shopee_shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection', to='shopee.shopeeshop')),
                ('tiktok_shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection', to='tiktok.tiktokshop')),
            ],
            options={
                'db_table': 'marketplace_connection',
                'unique_together': {('company', 'platform', 'display_name')},
            },
        ),
    ]
