# Generated by Django 5.2.7 on 2025-12-25 09:13

import core.models
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='shipping_config',
            field=models.JSONField(blank=True, default=core.models.Marketplace.get_default_shipping_config, help_text='Stores marketplace-specific shipping and insurance settings'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=django_ulid.models.ULIDField(db_column='company_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='id',
            field=django_ulid.models.ULIDField(db_column='marketplace_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
