# Generated by Django 5.2.7 on 2026-04-26 05:33

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('purchasing', '0007_alter_purchaseorder_status'),
        ('sales', '0002_add_so_return_number_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='accounts_payable_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.BigIntegerField()),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='purchasing.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='accounts_receivable_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('expected_amount', models.BigIntegerField()),
                ('settled_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Settlement'), ('SETTLED', 'Settled')], default='PENDING', max_length=20)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('marketplace_settlement_id', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='sales.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='payment_record_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('EWALLET', 'E-Wallet')], max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='finance/payment_proofs/')),
                ('note', models.TextField(blank=True, default='')),
                ('accounts_payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.accountspayable')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
