# Generated by Django 5.2.7 on 2025-12-13 13:23

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='category_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('total_qty', models.BigIntegerField(default=0)),
                ('total_cogs', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku_variant_code', models.CharField(max_length=100, unique=True)),
                ('current_cogs', models.BigIntegerField(default=0)),
                ('selling_price', models.BigIntegerField()),
                ('discounted_price', models.BigIntegerField(blank=True, null=True)),
                ('total_incoming_qty', models.IntegerField(default=0)),
                ('total_outgoing_qty', models.IntegerField(default=0)),
                ('total_available_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fake', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_master_warehouse', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCogs',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_cogs_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('price_rmb', models.BigIntegerField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cogs_amount', models.BigIntegerField()),
                ('original_qty', models.IntegerField(default=0)),
                ('remaining_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantMarketplace',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_marketplace_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.BigIntegerField()),
                ('discounted_price', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='core.marketplace')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('product_variant', 'marketplace')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantWarehouse',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('incoming_qty', models.IntegerField(default=0)),
                ('outgoing_qty', models.IntegerField(default=0)),
                ('physical_qty', models.IntegerField(default=0)),
                ('checkout_qty', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='inventory.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['product_variant', 'warehouse'], name='inventory_p_product_69cab7_idx')],
                'unique_together': {('product_variant', 'warehouse')},
            },
        ),
    ]
