# Generated by Django 5.2.7 on 2026-02-04 08:17

from core.utils import generate_ulid, get_default_shipping_config
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='category_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('total_qty', models.IntegerField(default=0)),
                ('total_cogs', models.IntegerField(default=0)),
                ('variant_options', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('product_photo', models.FileField(blank=True, null=True, upload_to='products/photos/')),
                ('weight', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_config', models.JSONField(blank=True, default=get_default_shipping_config, help_text='Stores marketplace-specific shipping and insurance settings')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku_variant_code', models.CharField(max_length=100, unique=True)),
                ('variant_values', models.JSONField(default=dict)),
                ('current_cogs', models.BigIntegerField(default=0)),
                ('base_price', models.BigIntegerField(default=0)),
                ('total_incoming_qty', models.IntegerField(default=0)),
                ('total_outgoing_qty', models.IntegerField(default=0)),
                ('total_available_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fake', models.BooleanField(default=False)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='warehouse_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_marketplace_visible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='stock_movement_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('PUR', 'Purchase Order'), ('IN', 'Inbound (Purchase/Restock)'), ('OUT', 'Outbound (Sales)'), ('ADJ', 'Stock Adjustment (Manual)'), ('TRF', 'Warehouse Transfer'), ('RET', 'Customer Return')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-cdate'],
            },
        ),
        migrations.CreateModel(
            name='ProductCogs',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_cogs_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('price_rmb', models.BigIntegerField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cogs_amount', models.BigIntegerField()),
                ('original_qty', models.IntegerField(default=0)),
                ('remaining_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantMarketplace',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_marketplace_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.BigIntegerField()),
                ('discounted_price', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='core.marketplace')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('product_variant', 'marketplace')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantWarehouse',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_variant_warehouse_id', default=generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('incoming_qty', models.IntegerField(default=0)),
                ('outgoing_qty', models.IntegerField(default=0)),
                ('physical_qty', models.IntegerField(default=0)),
                ('checkout_qty', models.IntegerField(default=0)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='inventory.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['product_variant', 'warehouse'], name='inventory_p_product_69cab7_idx')],
                'unique_together': {('product_variant', 'warehouse')},
            },
        ),
    ]
