# Generated by Django 5.2.7 on 2025-12-15 16:03

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='is_master_warehouse',
            new_name='is_marketplace_visible',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_ulid.models.ULIDField(db_column='category_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_cogs_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantmarketplace',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_marketplace_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantwarehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),

        migrations.RunSQL(
            sql="CREATE SEQUENCE product_sku_seq START WITH 1;",
            reverse_sql="DROP SEQUENCE product_sku_seq;"
        ),
        
        # 2. Trigger for Product (Main SKU)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_product_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                cat_code TEXT;
                seq_val INT;
            BEGIN
                seq_val := nextval('product_sku_seq');
                
                -- Use the explicit db_column 'category_id'
                SELECT category_code INTO cat_code 
                FROM inventory_category WHERE category_id = NEW.category_id;

                NEW.sku_code := UPPER(cat_code) || '-' || LPAD(seq_val::text, 3, '0');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_generate_sku
            BEFORE INSERT ON inventory_product
            FOR EACH ROW
            EXECUTE FUNCTION generate_product_sku();
            """,
            reverse_sql="""
            DROP TRIGGER trg_generate_sku ON inventory_product;
            DROP FUNCTION generate_product_sku();
            """
        ),

        # 3. Trigger for ProductVariant (Variant SKU)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_variant_sku()
            RETURNS TRIGGER AS $$
            DECLARE
                parent_sku TEXT;
                val1 TEXT;
                val2 TEXT;
            BEGIN
                -- Use the explicit db_column 'product_id'
                SELECT sku_code INTO parent_sku 
                FROM inventory_product WHERE product_id = NEW.product_id;

                val1 := NEW.variant_values->>'1';
                val2 := NEW.variant_values->>'2';

                NEW.sku_variant_code := parent_sku;
                
                IF val1 IS NOT NULL AND val1 != '' THEN
                    NEW.sku_variant_code := NEW.sku_variant_code || '-' || UPPER(val1);
                END IF;
                
                IF val2 IS NOT NULL AND val2 != '' THEN
                    NEW.sku_variant_code := NEW.sku_variant_code || '-' || UPPER(val2);
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_generate_variant_sku
            BEFORE INSERT ON inventory_productvariant
            FOR EACH ROW
            EXECUTE FUNCTION generate_variant_sku();
            """,
            reverse_sql="""
            DROP TRIGGER trg_generate_variant_sku ON inventory_productvariant;
            DROP FUNCTION generate_variant_sku();
            """
        )
    ]
