# Generated by Django 5.2.7 on 2025-12-25 06:01

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_is_master_warehouse_warehouse_is_marketplace_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_ulid.models.ULIDField(db_column='category_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_code',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_cogs_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantmarketplace',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_marketplace_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantwarehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
