# Generated by Django 5.2.7 on 2026-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_sku_sequence_and_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='field_change',
            field=models.CharField(default='', max_length=100),
        ),
    ]
