# Generated by Django 5.2.7 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_stockmovement_field_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcogs',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Source document reference (e.g., PO purchase_order_number)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='cogs_amount',
            field=models.BigIntegerField(help_text='Unit price in IDR = price_rmb * exchange_rate'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, help_text='Exchange rate from PO', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='original_qty',
            field=models.IntegerField(default=0, help_text='Total quantity that came in from PO (accumulates with each delivery)'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='price_rmb',
            field=models.BigIntegerField(help_text='Unit price in RMB (unit_price_foreign)'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='purchase_date',
            field=models.DateField(help_text='Date from PurchaseOrder.invoice_date'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='remaining_qty',
            field=models.IntegerField(default=0, help_text='Current available quantity. Only decreases on actual sales/outbound.'),
        ),
        migrations.AddIndex(
            model_name='productcogs',
            index=models.Index(fields=['product_variant', 'warehouse', 'reference_number'], name='inventory_p_product_c44007_idx'),
        ),
    ]
