# Generated by Django 5.2.7 on 2025-12-25 09:07

import apps.inventory.models
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productvariant_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_config',
            field=models.JSONField(blank=True, default=apps.inventory.models.Product.get_default_shipping_config, help_text='Stores marketplace-specific shipping and insurance settings'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_ulid.models.ULIDField(db_column='category_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_cogs_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantmarketplace',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_marketplace_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantwarehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='product_variant_warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=django_ulid.models.ULIDField(db_column='warehouse_id', default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
    ]
