# Generated by Django 5.2.7 on 2026-03-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productcogs_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcogs',
            name='allocated_delivery_fee',
            field=models.BigIntegerField(default=0, help_text='Delivery fee allocated per unit (IDR)'),
        ),
        migrations.AddField(
            model_name='productcogs',
            name='allocated_shipping_fee',
            field=models.BigIntegerField(default=0, help_text='Shipping fee allocated per unit (IDR)'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='exchange_rate',
            field=models.BigIntegerField(help_text='Exchange rate from PO (rounded integer)'),
        ),
        migrations.AlterField(
            model_name='productcogs',
            name='price_rmb',
            field=models.DecimalField(decimal_places=4, help_text='Unit price in RMB (unit_price_foreign)', max_digits=15),
        ),
    ]
