# Generated by Django 5.2.7 on 2026-05-04 16:07

import core.utils
import django.db.models.deletion
import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_profile'),
        ('inventory', '0005_add_allocated_fees_to_product_cogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='master_category_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', django_ulid.models.ULIDField(db_column='product_photo_id', default=core.utils.generate_ulid, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='products/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.product')),
            ],
            options={
                'db_table': 'product_photo',
                'ordering': ['order'],
            },
        ),
    ]
