# Generated by Django 5.2.7 on 2026-05-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_master_category_key_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmarketplace',
            name='shopee_item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantmarketplace',
            name='shopee_model_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
