# Generated by Django 5.2.7 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_add_shopee_ids_to_variant_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shopee_category_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
